### ISSUE TITLE
enhancement: all words search i.e. <dawn fraser>

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/PROV-Solr-API-Tools#16]
I just noticed a search for dawn fraser in the photowall returns the swimmer but also a ship named the African Dawn as well as newspaper articles about the steamer called the Dawn.  Is there any way to restrict search to All Words like the website search i.e.
https://prov.vic.gov.au/search_journey/select?keywords=dawn%20fraser&rows=10&start=10&iud=true&modifier=ALL_WORDS&advancedSearchStateQuery={%22keywords%22:%22dawn%20fraser%22,%22modifier%22:%22ALL_WORDS%22,%22start_date%22:%22%22,%22end_date%22:%22%22,%22iud%22:true}

**Comment by Conal-Tuohy** [comment]
A "phrase search" using double-quotes, i.e. `"dawn fraser"` should do the trick. And also `+dawn +fraser` should match any document containing both the word "dawn" and also the word "fraser" (the leading `+` means "must appear")

**Comment by Conal-Tuohy** [comment]
Maybe I could make it that if a form element included the token `phrasal` in its `class` attribute that its value would get passed to Solr wrapped in double-quotes (to make it a phrasal search)?

**Comment by asaletourneau** [comment]
As long as it doesn't make the UI too busy and increase your overall quote?

**Comment by Conal-Tuohy** [comment]
I altered the JS code so that an HTML form input that had the class `phrase` would be sent to Solr enclosed in double-quotes, which would then treat it as a phrase search. I modified the photo wall HTML page so that the input named `text` does have the class `phrase`:
```html
<input id="text-input" name="text" type="text" class="metadata phrase" placeholder="keywords...">
```
