### ISSUE TITLE
automation solution for photowall

### ISSUE THREAD

**Issue by asaletourneau** [Conal-Tuohy/PROV-Solr-API-Tools#17]
Currently the photowall is using manually entered series numbers to return digitised records from photographic series only. I offer the following solution to automate this after extensive testing:
create a query to return only digitised records from only photographic series for a given search term ;
1 Using the API query form I used text search term <school>
2. I faceted by photograph or image.
3. I ticked the iiif manifest checkbox.
4. 3,638 results come from photographic series only. Same for <melbourne> or any other term. I have done extensive testing and only photographic series records are ever returned. Please see if you can apply this automation solution to the PhotoWall tool to replace the existinmg manual approach. If it is at all possible to do this in time for our meeting next Wed 11/5 I would be verty grateful.

**Comment by Conal-Tuohy** [comment]
I will change the Photo Wall's form so that it doesn't refer to series at all, but instead restricts records to those whose `record_form` equals `Photograph or Image` and which also have some value for `iiif-manifest`. NB this is going to exclude the "Moving Image" records from series `12800`.

**Comment by Conal-Tuohy** [comment]
fixed in 12a36a791843a5eb36589abd6d928031773ea0df

**Comment by asaletourneau** [comment]
This all sounds great. There are no moving images in 12800. So should be good

**Comment by asaletourneau** [comment]
Just tested ans works perfectly! enjoy your break :)
